#!/bin/bash -x

#PBS -l mem=10g
#PBS -l vmem=10g
#PBS -l walltime=23:59:00
#PBS -l nodes=1:ppn=1
#PBS -o /hpf/largeprojects/cfcentre/strug/Naim/GTEX_44tissue/job_output/
#PBS -e /hpf/largeprojects/cfcentre/strug/Naim/GTEX_44tissue/job_output/
#PBS -d /hpf/largeprojects/cfcentre/strug/Naim/GTEX_44tissue/
#PBS -N compress_and_tabix

hostname
date

echo "Working dir is ${PBS_O_WORKDIR}"
cd $PBS_O_WORKDIR

# [[ DO STUFF ]]

echo "Done"
