#!/bin/bash -x

#PBS -l mem=65g
#PBS -l vmem=65g
#PBS -l walltime=3:59:00
#PBS -l nodes=1:ppn=1
#PBS -o /hpf/largeprojects/cfcentre/strug/faizan/job_output/
#PBS -e /hpf/largeprojects/cfcentre/strug/faizan/job_output/
#PBS -d /hpf/largeprojects/cfcentre/strug/faizan/
#PBS -N phewasSCL9A3_Ch5_March08

hostname
date

echo "Working dir is ${PBS_O_WORKDIR}"
cd $PBS_O_WORKDIR


module load R/3.4.0
Rscript phewas1script2v7_SCL9A3_Ch5.R > phewas1script2v7_SCL9A3_Ch5.Rout



echo "Done"

date
